### PR TITLE
Refresh prosody dockerfile

### PR DESCRIPTION
**Pull request by benbz**
This updates https://github.com/jitsi/docker-jitsi-meet/compare/master...matrix-org:jaywink/prosody-image-http-module against a newer upstream base and minimises how much we need to build

### CODE REVIEW

**Comment by benbz** [comment]
@jaywink just to highlight that as part of this I have pushed master & tags from upstream to this repo

**Comment by benbz** [comment]
Separately I'm wondering if we want to put the prosody module(s) directly into this dockerfile and then build/host the image somewhere

**Comment by jaywink** [comment]
> Separately I'm wondering if we want to put the prosody module(s) directly into this dockerfile and then build/host the image somewhere

That would probably make sense :+1: 

Note though that the need for the `http` module might disappear, depending on how the Prosody module is made async. However, a custom docker image would still make sense to bundle everything together nicely.

**Comment by benbz** [comment]
I'd be strongly in favour of getting rid of the need for the `http` dependency, would allow us to simply extend the upstream image for Docker and less things to install for non-Docker.

**Comment by jaywink** [comment]
I [tried](https://github.com/matrix-org/prosody-mod-auth-matrix-user-verification/pull/9) :P It was late at night. It crashed prosody. We need to find time to make something like that work.

**Pull request merged**
