### PR TITLE
Consolidated Docker CI workflows with proper dependencies

### PR DESCRIPTION
**Pull request by Arkaniad**
This modification will allow all the Docker images for Jitsi Meet to be built in one end to end pipeline, properly using the new build's base images for the dependent image builds within the branch/pr/tag. Also will run on a 'testing' branch with a separate tag. This will allow us to do the building/testing necessary for [this PR](https://github.com/matrix-org/docker-jitsi-meet/pull/15) which involves overhauling the base images completely since the existing builds still use the upstream base images and hosting the testing branch images will allow for testing the in an actual cluster without touching the release images.

### CODE REVIEW

**Comment by Arkaniad** [comment]
hm, seems this may need some attention before merging:

```
buildx failed with: error: failed to solve: failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "ghcr.io/matrix-org/docker-jitsi-meet/base:17/merge": invalid reference format
```

Looks like the `${{ github.ref_name }}` parameter isn't working as expected..

**Comment by Arkaniad** [comment]
Looks like that did the trick :)

**Review by benbz — APPROVED** [review]
LGTM. I had a quick think about whether it was worth merging the 2 `docker/build-push-action` steps down by having a variable containing the correct `BASE_TAG` but thought that would be confusing.

The only improvement I came up with was to investigate whether [resusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows) would remove all the repetition for each image. What's here is good though

**Comment by Arkaniad** [comment]
Agreed on both points and noted for later :)

**Pull request merged**
